# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: validator

on:
  workflow_dispatch:
  push:
    paths:
      - validator/**

jobs:
  test:
    name: 🧪 Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: 👍 Checkout
        uses: actions/checkout@v4

      - name: ❇️ Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: 📥 Install Dependencies
        run: npm install

      - name: 🧑‍🔬 Tests
        run: "npm run validator:test"

  publish:
    name: 🚀 Publish
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: 👍 Checkout
        uses: actions/checkout@v4

      - name: ❇️ Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"

      - name: 📥 Install Dependencies
        run: npm install

      - name: 🛠️ Build monorepo deps
        run: npm run valibot:numbers:build && npm run zod:numbers:build

      - name: 🛠️ Build
        run: npm run validator:build

      - name: 🚀 Publish to npm
        run: "npm publish --access public --workspace=@schemasjs/validator"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
